version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=watercontainment
      - POSTGRES_PASSWORD=watercontainment123
      - POSTGRES_DB=watercontainment
    ports:
      - "5432:5432"
  water-containment:
    build:
      context: .
    ports:
      - "8081:8080"
    links:
      - db
    depends_on:
      - db
